language: python
python:
#  - "3.3" will be nice in future
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
    - sudo apt-get install libzmq3-dev libavahi-compat-libdnssd-dev
    - gem install bundler
    - sudo npm install -g grunt-cli

install:
    - npm install
    - grunt install
    - pip install -r requirements/test.txt

# command to run tests, e.g. python setup.py test
script:  grunt test