language: python
python:
#  - "3.3" will be nice in future
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
    - sudo apt-get install libzmq3-dev libavahi-compat-libdnssd-dev ruby2.0
    - gem install bundler
    - npm install 1 -g grunt-cli
    - npm install

install:
    - pip install -r requirements/test.txt
    - grunt install

# command to run tests, e.g. python setup.py test
script:  grunt test